### ISSUE TITLE
Unexpected API error

### ISSUE THREAD

**Issue by jackplug** [nicolasm/ulauncher-pinboard-search#1]
I am not *totally* sure whether this is a problem with the extension, but I am having a problem:

```Unexpected API error. KeyError: com.github.nicolasm.ulauncher-pinboard-search```

Steps to reproduce:
Install extension, enter Pinboard API token and pinboard username. Click **Save** button.

I checked that those values are correct :-) I even regenerated a new API token and tried again.

**Comment by nicolasm** [comment]
Hi,
Have you tried to launch Ulauncher from the terminal in verbose mode?

I have tried to reproduce your error but I didn't get your error.

**Comment by jackplug** [comment]
I completely reinstalled Xubuntu (not for this reason, but I had some unrelated issues) and I am still seeing the same problem. On running ``ulauncher --verbose`` I see the following

```
(ulauncher:12554): Gtk-WARNING **: 21:54:22.444: Theme parsing error: gtk.css:4419:85: '/*' in comment block

(ulauncher:12554): Gtk-WARNING **: 21:54:22.445: Theme parsing error: gtk.css:4512:64: '/*' in comment block
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
```

If I simply run ``ulauncher``, I get a little more info related to the extension:

```
Traceback (most recent call last):
  File "/home/<USER>/.cache/ulauncher_cache/extensions/com.github.nicolasm.ulauncher-pinboard-search/main.py", line 15, in <module>
    from pinboard import start_async_pinboard_download
  File "/home/<USER>/.cache/ulauncher_cache/extensions/com.github.nicolasm.ulauncher-pinboard-search/pinboard.py", line 3, in <module>
    import requests
ImportError: No module named requests
2019-05-21 21:58:03,636 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.nicolasm.ulauncher-pinboard-search" exited instantly with code 1
```

If I attempt to add/save my Pinboard credentials, I see (at the same time as the message described initially):

```
2019-05-21 22:02:05,479 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: com.github.nicolasm.ulauncher-pinboard-search
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.nicolasm.ulauncher-pinboard-search'
```

Is that any help?

Other info:

- I used the https://github.com/nicolasm/ulauncher-pinboard-search url to install
- I setup pip2 and installed simplejson before install
- my API token and Pinboard user name are not being saved when I close the settings box (possibly no help, or possibly something permission-related?)

Many thanks for taking a look, and if you decide to investigate further, let me know if you need more info

**Comment by nicolasm** [comment]
Hi,
In the logs you provided:
import requests
ImportError: No module named requests

You need to install the module with pip.

Tell me if it solves your issue.
