### ISSUE TITLE
Pinboard extension doesn't install

### ISSUE THREAD

**Issue by TerryNorton** [nicolasm/ulauncher-pinboard-search#3]
Message: 'com.github.nicolasm.ulauncher-pinboard-search'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.8/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.8/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 425, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.8/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.nicolasm.ulauncher-pinboard-search'

```
I had a look at the two other similar errors, but it's all Greek to me. I installed uLauncher today on Manjaro 19. This Pinboard extension is the only one I've tried installing.

I read you're are using Rofi instead of uLauncher. Is Rofi better? The primary add-on I'm looking to use is Pinboard. On my Mac it works great using the Alfred launcher.

**Comment by TerryNorton** [comment]
I've been searching for the way to install using pip in the terminal. What's the syntax to install using pip?

**Comment by nicolasm** [comment]
I use Rofi as a launcher but I kept Ulauncher for accessing my Pinboard bookmarks.

`sudo pip install -r requirements.txt`
